server:
  port: 9098

spring:
  data:
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456789
    ddl-auto: create
    default_schema: public

hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect