server:
  port: 9098

spring:
  data:
    jpa:
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/sqlite-to-postgres
    username: postgres
    password: 123456789
    ddl-auto: none
    default_schema: public

hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect